[workspace]
channels = ["conda-forge", "bioconda", "pytorch"]
name = "ensirna_env"
platforms = ["linux-64"]
version = "0.1.1"

[tasks]

[dependencies]
viennarna = ">=2.6.4,<3"
python = "3.10.*"
biopython = "*"
numpy = "*"
pandas = "*"
scipy = "*"
tensorboard = ">=2.20.0,<3"
tqdm = "*"
openpyxl = "*"
scikit-learn = ">=1.7.2,<2"
rdkit = ">=2026.3.2,<2027"
xgboost = ">=3.2.0,<4"

pytorch = { version = ">=2.0", channel = "pytorch" }

[pypi-dependencies]
rna-fm = "*"
torch-geometric = "*"